version: "3.3"
services:
  fake-service:
    build: .
    image: fake-service
    command: 
        - "-m"
        - "fs"
        - "--fs-folders"
        - "data:/data/fake-service"
    ports:
      - "8080:8080"