apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-service-data-volumeclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi