apiVersion: v1
kind: Service
metadata:
  name: fake-service
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /prometheus/metrics
        prometheus.io/port: "8080"
spec:
  selector:
    app: fake-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080