apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service-deployment
  labels:
    app: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      labels:
        app: fake-service
    spec:
      volumes:
      - name: fake-service-storage
        persistentVolumeClaim:
          claimName: fake-service-data-volumeclaim
      containers:
      - name: fake-service2
        image: fake-service
        args: ["--fs-folders", "data:/home/app/fake-service-data"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/home/app/fake-service-data"
          name: fake-service-storage
        imagePullPolicy: Never